
export const DEFAULT_PARAMS = {
  hourly_rate: 8500,
  cost_per_cm2: 0.75,
  iva: 0.19,
  waste: 0.2,
  profit_margin_final: 0.35,
  profit_margin_publisher: 0.20,
  min_operative: 20000,
  tube_cost_factor: 40,
  ojal_cost: 300,
  stick_cost: 5000
};

export const PRODUCT_DESIGN_TIMES: Record<string, number> = {
  "BANNER IMPRESIÓN GRAN FORMATO EN LONA BANNER DE ALTA CALIDAD": 30,
  "PANAFLEX": 45,
  "IMPRESIÓN EN VINILO": 45,
  "IMPRESIÓN EN VINILO + LAMINADO": 45,
  "VINILO TRANSPARENTE INTERNO": 45,
  "VINILO MICROPERFORADO": 45,
  "VINILO+BASE EN PVC": 45,
  "floorgraphic": 45,
  "PENDONES": 30,
  "PENDON MAS OJALES": 30,
  "PENDON SIN OJALES": 30,
  "PASACALLES": 30,
  "CARTON + VINILO": 30,
  "ESMERILADO": 45,
  "LONA+LAMINADO": 45,
  "IMANTADOS LAMINA GRUESA": 30,
  "IMANTADOS LAMINA DELGADA": 25,
  "VINILO+MDF": 30,
  "IMPRESIÓN EN VINILO REFLECTIVO": 45
};

export const DESIGN_COST_BY_MINUTES: Record<number, number> = {
  15: 13750, 25: 13750, 30: 13750, 45: 13750, 60: 13750, 75: 13750
};

export const PRODUCT_PRICES_FINAL: Record<string, number> = {
  "BANNER IMPRESIÓN GRAN FORMATO EN LONA BANNER DE ALTA CALIDAD": 1.3,
  "PANAFLEX": 1.7,
  "IMPRESIÓN EN VINILO": 1.7,
  "IMPRESIÓN EN VINILO + LAMINADO": 2.4,
  "VINILO MICROPERFORADO": 1.8,
  "VINILO+BASE EN PVC": 5.7,
  "floorgraphic": 3.2,
  "PENDONES": 2.0,
  "PENDON MAS OJALES": 1.4,
  "PENDON SIN OJALES": 1.3,
  "PASACALLES": 1.3,
  "CARTON + VINILO": 2.5,
  "ESMERILADO": 1.8,
  "LONA+LAMINADO": 2.0,
  "IMANTADOS LAMINA GRUESA": 23.8,
  "IMANTADOS LAMINA DELGADA": 4.4,
  "VINILO+MDF": 13.0,
  "IMPRESIÓN EN VINILO REFLECTIVO": 2.5
};

export const PRODUCT_PRICES_PUBLISHER: Record<string, number> = {
  "BANNER IMPRESIÓN GRAN FORMATO EN LONA BANNER DE ALTA CALIDAD": 1.36,
  "PANAFLEX": 1.70,
  "IMPRESIÓN EN VINILO": 1.70,
  "IMPRESIÓN EN VINILO + LAMINADO": 2.4,
  "VINILO MICROPERFORADO": 1.8,
  "VINILO+BASE EN PVC": 5.7,
  "floorgraphic": 3.2,
  "PENDONES": 1.36,
  "PENDON MAS OJALES": 1.36,
  "PENDON SIN OJALES": 1.36,
  "PASACALLES": 1.36,
  "CARTON + VINILO": 2.5,
  "ESMERILADO": 1.8,
  "LONA+LAMINADO": 2.3,
  "IMANTADOS LAMINA GRUESA": 23.8,
  "IMANTADOS LAMINA DELGADA": 4.4,
  "VINILO+MDF": 13.0,
  "IMPRESIÓN EN VINILO REFLECTIVO": 2.5
};

export const ROLL_WIDTHS = [75, 102, 122, 152];
